# Generated by Django 5.1.6 on 2025-02-22 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('news_url', models.URLField(max_length=500, verbose_name='URL de la noticia')),
                ('extracted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de extracción')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'news',
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150, verbose_name='Producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('variation', models.CharField(max_length=50, verbose_name='Variación')),
                ('unit_measure', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Precio de Producto',
                'verbose_name_plural': 'Precios de Productos',
                'db_table': 'product_prices',
                'ordering': ['-updated_at'],
            },
        ),
    ]
